sudo: true
dist: trusty
language: c
before_install:
- openssl aes-256-cbc -K $encrypted_7d306b01dc1f_key -iv $encrypted_7d306b01dc1f_iv -in script/secrets.tar.enc -out script/secrets.tar -d
- tar xvf script/secrets.tar -C script/
- sudo apt-get update -qq
- sudo apt-get install -qq binutils-dev genisoimage liblzma-dev syslinux
- sudo pip install mkdocs mkdocs-bootswatch awscli
script:
- "./script/prep-release.sh"
deploy:
  - provider: s3
    access_key_id:
      secure: Qj6f8iJXio6IXsKukoVbltfkYt7yDjwPi/Ozfc135dX4tZCerILnZ972erPUuxt7xw0anB5+2qdBysQuXJBI4AkigaYXCwIQ40VTKUQ94N7+qRdYhDj/Y28joAVDQ8uN/NOAm1Dpu+RQEWhGGN8cWmKOVcufzsVfkoeaoIhdFEnPnSVf9T92PlHCmU87nWa9iTorfG0LOXAloywPI0jFiUU9A9p0F1uD+y7gdghKndTFZaAxReV+a6Yk3i+QliL/+Sak0wgU/Skg3XQ5nKA5R14CJTKskH+r2/vBWHVauhok2blfxZG5d7XPztoXIkjHcDmxCQP5vD2VpU1ZUWCk8yRn2DcTEgkiWfTm1QRDGf9Z584RUKbQ+Ia/6xLwyqSDlYmfxX1bSm1qywvK0S0weMfFJxbdDcouZLmbze2iSmENyHQycGgfDlN/RpsQPcsR49XKZ35+sY2o6fuywtFVCRWalMH2pRDzDhBuO3NYI4AQ0N/JYyg360xL7mN+tn9C6zOSvk+lwJtZUstAIFV+P3qbfKdYSEe90qtcvQyLCzfHf04pG4ip7ot/OPZLJnVQM+AjBVWBKDUrvQ6gNsnc4t2FDd3KGLcwsY9dxpf9kZBLdVX0eiHQnhPgfrjzHkav3yRAgH0EbEh4R9Z5oFlyV2ERs0sEQV3hQLRj02J9W4c= 
    secret_access_key:
      secure: H6TlCD+Ar/g4pqMDSEa8UDzYaOiFuYki+eOPaUO1T6KBNiIah5Fq8bRyrv9Wtovk+XyTchD+UEZv0G0JEYvEMbsis7QThyb7NIKGm3jnzjQ+FgFXGsRqhGe1wdFB22CRQ46uSCdFqkm2GQWhMcokzBh4vZDVHVCMZ+SjcSrowL8x4pNJtlJK4nqZEK8BmgqAe4VLBBvkLJHYTHJ/Qx9q9RIweEFNcdkdFamHqo/3iwQSc+qXobe5f3p+vQY8GvfhsrBnnYNmiOjXAnNSK2Rmsd9TloYR2bGRnwxhQc7ZFLjeil/9j3g+WEHj7tsbCOnscFxomj2Z7CaKxjPS+9tQkwOa/v/1cg5Rmp76QxcvMQWlU0ToGUeX435KIzI6nKJnOwBq1HtEbjWfptanlW1P1SjAV0UWK8m0cYSU2qLNTRTww115M6DTNq3sS5eu7TUgwJlzNxF4HbauQTU/jN6hS5DrLwaBaAiteeVeQ21yUvT/HTmooC9YxKCI4gsh4ajvdf7TQU5H70HljlHp/PiJmRa3TK/+SSY87u7CH6ZfW9ZfHy3zPkYGhJU250agf68BVL0OdOH1I6LuYHsSJfW25RHhX7cH7RvBNOqKsw0Vb9Npzr1gXPTBAjFCzgPOPqwfCFUGa25/9A0lKxrZ6/bKKH2IfQnTxIYb68dW368YTco= 
    bucket:
      secure: gJvHGjDplM+x7maPhN0QKP3M8r7ErO3vwpokfUR/KaFNYQvMxZGuI0w27Mfoku8NFrH0YYBv2yvuOFywxWdfyVEzMFimOFUrAhkizqiPtzVBkD10EUBqaQRxwI6JuuovxYdwO2QiInCdpT02vtFjDPILz1ouXq+VpKJWxncHmC1SSEw3eUlJTQWpuh0a/6vSqVjygmqknj+PW0LaI6i/vEeU8iDw+z5mAYyzs8HIlpmDAcjNTi8WkAETMHLjRoXfd6CYDM/CrbnILu568/jAcjlBE2lmZ/UhOar/bbmmUH4ve1GPHBtnTTBVwFA3B84pRZW/Iz7+BEuwoWbGMX6XClhz7NpuvNJfTEN2KMbKAvYcRpk2EYsaywq5kaZWT209frB8Jergvw5v8IetHzu+mUwBQsHr5M0f6pSmOwy/CesClfJBO5v5NpqqtVtPPbPo/4Oxpg4l/3EMXVSilf6tdIxlp5OmxrdjF6SV/n0OhnhRt1Wj+1U+VvDEK0aYxSCIWZCHLrRBaDxB3zK9yKa5GyKcbdC32i1OV8eEJwjnlvaUUllEID2Hlv34rn5K0r51NMbxuibPklSet0/MFFfcK8/5lAP9ZY3/SofUuSyQ9CbxYUDgO5eiG1Q/bCxqcGVoB/rkJwjTHvMU1oTEKDZq0mhKZAqe6s+cUNOYoxIyvwg=
    local_dir: build
    skip_cleanup: true
    on:
      repo: antonym/netboot.xyz
  - provider: s3
    access_key_id:
      secure: Qj6f8iJXio6IXsKukoVbltfkYt7yDjwPi/Ozfc135dX4tZCerILnZ972erPUuxt7xw0anB5+2qdBysQuXJBI4AkigaYXCwIQ40VTKUQ94N7+qRdYhDj/Y28joAVDQ8uN/NOAm1Dpu+RQEWhGGN8cWmKOVcufzsVfkoeaoIhdFEnPnSVf9T92PlHCmU87nWa9iTorfG0LOXAloywPI0jFiUU9A9p0F1uD+y7gdghKndTFZaAxReV+a6Yk3i+QliL/+Sak0wgU/Skg3XQ5nKA5R14CJTKskH+r2/vBWHVauhok2blfxZG5d7XPztoXIkjHcDmxCQP5vD2VpU1ZUWCk8yRn2DcTEgkiWfTm1QRDGf9Z584RUKbQ+Ia/6xLwyqSDlYmfxX1bSm1qywvK0S0weMfFJxbdDcouZLmbze2iSmENyHQycGgfDlN/RpsQPcsR49XKZ35+sY2o6fuywtFVCRWalMH2pRDzDhBuO3NYI4AQ0N/JYyg360xL7mN+tn9C6zOSvk+lwJtZUstAIFV+P3qbfKdYSEe90qtcvQyLCzfHf04pG4ip7ot/OPZLJnVQM+AjBVWBKDUrvQ6gNsnc4t2FDd3KGLcwsY9dxpf9kZBLdVX0eiHQnhPgfrjzHkav3yRAgH0EbEh4R9Z5oFlyV2ERs0sEQV3hQLRj02J9W4c=
    secret_access_key:
      secure: H6TlCD+Ar/g4pqMDSEa8UDzYaOiFuYki+eOPaUO1T6KBNiIah5Fq8bRyrv9Wtovk+XyTchD+UEZv0G0JEYvEMbsis7QThyb7NIKGm3jnzjQ+FgFXGsRqhGe1wdFB22CRQ46uSCdFqkm2GQWhMcokzBh4vZDVHVCMZ+SjcSrowL8x4pNJtlJK4nqZEK8BmgqAe4VLBBvkLJHYTHJ/Qx9q9RIweEFNcdkdFamHqo/3iwQSc+qXobe5f3p+vQY8GvfhsrBnnYNmiOjXAnNSK2Rmsd9TloYR2bGRnwxhQc7ZFLjeil/9j3g+WEHj7tsbCOnscFxomj2Z7CaKxjPS+9tQkwOa/v/1cg5Rmp76QxcvMQWlU0ToGUeX435KIzI6nKJnOwBq1HtEbjWfptanlW1P1SjAV0UWK8m0cYSU2qLNTRTww115M6DTNq3sS5eu7TUgwJlzNxF4HbauQTU/jN6hS5DrLwaBaAiteeVeQ21yUvT/HTmooC9YxKCI4gsh4ajvdf7TQU5H70HljlHp/PiJmRa3TK/+SSY87u7CH6ZfW9ZfHy3zPkYGhJU250agf68BVL0OdOH1I6LuYHsSJfW25RHhX7cH7RvBNOqKsw0Vb9Npzr1gXPTBAjFCzgPOPqwfCFUGa25/9A0lKxrZ6/bKKH2IfQnTxIYb68dW368YTco=
    bucket:
      secure: "KOLFTGl65fXGimKr+AIUMAvoS3t8kpsMr7n5zjtPMd8fRf3JmH5eFZhzLiDtyMCLMQo+KJDCM9daD8JCENZRgY5NTzJ6Dmj+xRgrzTAhSkXQkN3MdsZid1+J8+mJElNOnyyp2nwl5OqYpeIaGYE0YcpcvddsERqwzpgnWPkUPGJNPEyiUdWMa28X3VJN8NzYLqUZVjHOFDoptH44TvIhc1fEl0GIJEbIHpOkSe0TZiBLKGM1sLM/SvkbTVrrOeICJovXFz0LJsQjbA5gw9lBg9rXrhJ+gDjtYY7M1Z3TOAauXHYUwFZ843Dg5T5OQ9J6sYxujb5QBjr7VEeB96ixEtuuFGY64dVvvChLEtrq+EELFm08vJFpUtf4YgNAoOd1oRaUCpWxTl7jDIxsyErxVyoCVPswrSu+gIZhTY8+aOtaLfEzQ4I82XQoQn6pgk8ykgEWrbZn1kIRog+s9fBwU/ZXLPd9WhGBa47xDoIYBNuFYrZZFuTsdA5ejDxmkc4Jvm81cwU+t16KLsmh6WqpLLjhMYMFpsj2Vn6lYZrtFqG+WuxNcMzOBABiQxNsgvYJ6K239FbPQxgkvk8NnK87EFrzO9lb7dIFHTFRe/JCy7KUxvCIdd/SEDWmOz9AFlqIX+9k76Q2mc4f2EymrCU22kwnUHZD8+YIMRJ4Nmh+47A="
    local_dir: site
    skip_cleanup: true
    on:
      repo: antonym/netboot.xyz

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID_BOOT --paths "/*"
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID_SITE --paths "/*"

notifications:
  email:
    - antony@mes.ser.li
